apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: elasticsearch-staging-mysql-volume-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  capacity:
    storage: 50Gi
  csi:
    volumeAttributes:
      server: "3766a4a783-jsy8.cn-shanghai.nas.aliyuncs.com"
      path: "/mnt/elasticsearch-staging-mysql-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: default
spec:
  resources:
    requests:
      storage: 50Gi
