apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx
  labels:
    app: backend-nginx
spec:
  selector:
    matchLabels:
      app: backend-nginx
      tier: backend-nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-nginx
        tier: backend-nginx
    spec:
      containers:
        - image: null
          name: backend-nginx
          ports:
            - containerPort: 80
          command:
            [
              "sh",
              "-c",
              "sed -i '2s/php/$(UPSTREAM_ADMIN)/' /etc/nginx/conf.d/default.conf; exec nginx -g 'daemon off;'",
            ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-php
  labels:
    app: backend-php
spec:
  selector:
    matchLabels:
      app: backend-php
      tier: backend-php
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-php
        tier: backend-php
    spec:
      volumes:
        #      - name: php-env
        #        configMap:
        #          name:  backend-php-env
        - name: yii-runtime
          persistentVolumeClaim:
            claimName: null
      containers:
        - image: null
          name: backend-php
          volumeMounts:
            #        - name: php-env
            #          mountPath: "/var/www/html/.env"
            #          subPath: env
            - name: yii-runtime
              mountPath: /var/www/html/runtime
          envFrom:
            - configMapRef:
                name: public-overlays
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_PASSWORD
            - name: REDIS_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_SESSION_PASSWORD
            - name: REDIS_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_SEARCH_PASSWORD
