variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1

cache:
  key: ${CI_PROJECT_NAME}_2
  paths:
    - src/vendor

stages:
  - install
  - build
  - deploy

before_script:
  - set -aeu
  # - docker login ${DOMAIN_DOCKER_REGISTRY} -u ${DOMAIN_DOCKER_REGISTRY_USERNAME} -p${DOMAIN_DOCKER_REGISTRY_PASSWORD}
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - cp .env.default .env

after_script:
  - source .env
  - ./deploy/scripts/clean-docker-network.sh  "${PROJECT}_${ENVIRONMENT}_default"

###########################################################################

staging-install-job:
  stage: install
  environment:
    name: staging
  image: composer:2
  tags:
    - yaoin-net:aliyun-small-2
  script:
    - cd ./src
    - echo "Start install php packages"
    - composer install --ignore-platform-reqs
    - composer dump-autoload
    - cd ../

build-staging-job:
  stage: build
  environment:
    name: staging
  tags:
    - yaoin-net:aliyun-small-2
  only:
    - develop
  script:
    # - ./deploy/scripts/enable-docker-compose-network.sh
    - ./deploy/scripts/update-resource-mirror.sh
    - ./deploy/scripts/modify-dot-env-staging.sh
    - sed -i "1 s|$|-${CI_COMMIT_SHA:0:8}|" VERSION
    - source ./.env
    - export COMPOSE_PROJECT_NAME="${PROJECT}_${ENVIRONMENT}"
    - export VERSION=$(cat VERSION)
    - ./docker-compose up -d
    - docker ps
    - ./codecept run unit
    - ./docker-compose stop
    # - ./apidoc
    # - ./codecept run
    # - ./deploy/scripts/push-to-gitlab.sh
    - echo "test passed, ready to build and push to Aliyun CS"
    - echo "built successfully"
  # when: manual
