variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1

cache:
  key: ${CI_PROJECT_NAME}_3
  paths:
    - src/vendor

stages:
  - install
  - test
  - build
  - deploy

before_script:
  - set -aeu
  # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - cp .env.default .env

after_script:
  - source .env
  - ./deploy/scripts/clean-docker-network.sh  "${PROJECT}_${ENVIRONMENT}_default"

###########################################################################

staging-install-job:
  stage: install
  environment:
    name: staging
  image: composer:2
  tags:
    - 818ps_web_dev
  only:
    - develop
    - testing
  script:
    - cd ./src
    - echo "Start install php packages"
    - composer install --ignore-platform-reqs

staging-testing-job:
  stage: test
  environment:
    name: staging
  image: yao3060/yii2-php:8-fpm-alpine
  tags:
    - 818ps_web_dev
  only:
    - testing
  script:
    - echo "testing"
    - echo $(pwd)
    - ls -la
    - source ./.env
    - cd src
    # Run webserver
    - php -S localhost:8085 --docroot web &>/dev/null&
    - ./vendor/bin/codecept run unit

build-staging-job:
  stage: build
  environment:
    name: staging
  tags:
    - 818ps_web_dev
  only:
    - develop
  script:
    # - ./deploy/scripts/enable-docker-compose-network.sh
    - ./deploy/scripts/update-resource-mirror.sh
    - ./deploy/scripts/modify-dot-env-staging.sh
    - sed -i "1 s|$|-${CI_COMMIT_SHA:0:8}|" VERSION
    - source ./.env
    - export COMPOSE_PROJECT_NAME="${PROJECT}_${ENVIRONMENT}"
    - export VERSION=$(cat VERSION)
    - echo $VERSION
    - echo "ready to build and push to Aliyun CS"
    - ./deploy/scripts/deploy-to-aliyun-cs.sh nginx php
    - echo "built successfully"
  when: manual
