variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  KUBECONFIG: /etc/deploy/config

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test

###########################################################################

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]
  only:
    - testing
  script:
    - echo "do code_quality test"
