#!/usr/bin/env bash
set -aeuo pipefail

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

source .env

NETWORK=$(basename "$PWD")_${ENVIRONMENT}_default

./docker-compose exec -d php ./vendor/bin/codecept $@
