#!/usr/bin/env bash
set -aeuo pipefail

# Doc: https://hub.docker.com/r/codeclimate/codeclimate

docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate
