version: "2.3"

services:
  nginx:
    # image: ${CONTAINER_REGISTRY}/${ENVIRONMENT}_nginx:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"

  php:
    # image: ${CONTAINER_REGISTRY}/${ENVIRONMENT}_php:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    restart: always
    env_file: .env

  mysql:
    image: ${DB_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  cache:
    image: redis:5.0-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_cache
    restart: always
    expose:
      - "6379"

volumes:
  mysql-db:
