version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    restart: "no"
    depends_on:
      - php
    volumes:
      - ./src/web:/var/www/html/web:delegated

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
      target: php
      extra_hosts:
        - codeload.github.com:192.30.255.121
    restart: "no"
    user: ${DOCKER_HOST_UID}:www-data
    depends_on:
      - mysql
      - cache
    environment:
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    restart: "no"
    volumes:
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  cache:
    restart: "no"

  elasticsearch:
    restart: "no"
