version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    restart: "no"
    depends_on:
      - php
    volumes:
      - ./src/web:/var/www/html/web:delegated

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
      target: php
      extra_hosts:
        - codeload.github.com:192.30.255.121
    restart: "no"
    user: ${DOCKER_HOST_UID}:www-data
    depends_on:
      - mysql
      - cache
    environment:
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    restart: "no"
    volumes:
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  cache:
    image: redis:5.0-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: always
    expose:
      - "6379"

  elasticsearch:
    image: elasticsearch:5.6.3-alpine
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=cache
      - REDIS_1_PORT=6379
    depends_on:
      - cache
    ports:
      - "8082:80"
