@BASE_URL = http://localhost:8081


### Get Logs
GET {{BASE_URL}}/v1/logs?name=hanmaker&email=email@email.com&age=11 HTTP/1.1
content-type: application/json
# username:password
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
