@BASE_URL = http://localhost:8081

### Test
GET {{BASE_URL}}/?test=1 HTTP/1.1
content-type: application/json
Accept: application/json
X-UserId: 1111
X-Username: yyyy
X-UserType: 1
X-Roles: user
X-FORWARDED-FOR: 1.1.1.1
X-ORIGINAL-FORWARDED-FOR: 2.2.2.2

### Get Logs
GET {{BASE_URL}}/v1/logs?name=hanmaker&email=email@email.com&age=11 HTTP/1.1
content-type: application/json
Accept: application/json
X-UserId: 1111
X-Username: yyyy
X-UserType: 1
X-Roles: user
X-FORWARDED-FOR: 1.1.1.1
# X-ORIGINAL-FORWARDED-FOR: 1.1.1.1

### get Assets
GET {{BASE_URL}}/v1/assets?keyword=你好&page=3&pageSize=30&sceneId=0&isZb=1
Content-Type: application/json
Accept: application/json


### 违禁词验证
POST {{BASE_URL}}/v1/sensitive-words/validate
Content-Type: application/json
Accept: application/json

{
	"keyword": "党政"
}


### H5 违禁词验证
POST {{BASE_URL}}/v1/h5-sensitive-words/validate
Content-Type: application/json
Accept: application/json

{
	"keyword": "党政"
}


### 背景视频搜索
GET {{BASE_URL}}/v1/background-videos?keyword=0
Content-Type: application/json
Accept: application/json

### 裁剪搜索
GET {{BASE_URL}}/v1/containers?keyword=0
Content-Type: application/json
Accept: application/json

### 设计师模板
GET {{BASE_URL}}/v1/designer-templates?keyword=0
Content-Type: application/json
Accept: application/json
X-UserId: 1111
X-Username: yyyy
X-UserType: 1
X-Roles: user
x_forward_for: 123.123.123.13

### Git 搜索
GET {{BASE_URL}}/v1/gif-assets?keyword=你好
Content-Type: application/json
Accept: application/json

### 组合字搜索
GET {{BASE_URL}}/v1/groups?keyword=0&search=你好&search_all=1
Content-Type: application/json
Accept: application/json

### 设计师动效
GET {{BASE_URL}}/v1/lottie-videos?keyword=
Content-Type: application/json
Accept: application/json

### 设计师动效搜索词
GET {{BASE_URL}}/v1/lottie-video-words
Content-Type: application/json
Accept: application/json

### 图片素材搜索
GET {{BASE_URL}}/v1/pictures?keyword=早安
Content-Type: application/json
Accept: application/json

#### 富文本元素
GET {{BASE_URL}}/v1/rich-editor-assets?keyword=0&page=1
Content-Type: application/json
Accept: application/json

### SVG
GET {{BASE_URL}}/v1/svg?keyword=0
Content-Type: application/json
Accept: application/json

### 关键词搜索
GET {{BASE_URL}}/v1/keywords?keyword=中秋&type=1&page_size=30
Content-Type: application/json
Accept: application/json

### seo词库相关推荐
GET {{BASE_URL}}/v1/seo/keyword-assets?keyword=节日
Content-Type: application/json
Accept: application/json

### PPT模板单页分类筛选
GET {{BASE_URL}}/v1/ppt-templates?class_id=1
Content-Type: application/json
Accept: application/json

### 视频元素搜索
GET {{BASE_URL}}/v1/video-elements?keyword=可爱&class_id=188&scope_type=lottie
Content-Type: application/json
Accept: application/json

### 片段视频
GET {{BASE_URL}}/v1/video-templates?keyword=
Content-Type: application/json
Accept: application/json
