version: "2.3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: nginx
    restart: "no"
    depends_on:
      - php
    volumes:
      - ./src/web:/var/www/html/web:delegated

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        ALPINE_LINUX_MIRROR: ${ALPINE_LINUX_MIRROR}
        APP_ENV: ${APP_ENV}
      target: php
      extra_hosts:
        - codeload.github.com:192.30.255.121
    restart: "no"
    user: ${DOCKER_HOST_UID}:www-data
    depends_on:
      - mysql
      - cache
    environment:
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - default
      - base_share_network

  mysql:
    restart: "no"

  cache:
    restart: "no"

networks:
  base_share_network:
    external: true

  
