version: "2.3"

services:
  laravel_nginx:
    image: ${CONTAINER_REGISTRY}/${PROJECT}_${ENVIRONMENT}_laravel_nginx:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_nginx
    restart: always
    ports:
      - "${LARAVEL_HTTP_PORT}:80"

  laravel_php:
    image: ${CONTAINER_REGISTRY}/${PROJECT}_${ENVIRONMENT}_laravel_php:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_php
    restart: always
    env_file: .env
    volumes:
      - laravel-storage:/var/www/html/storage

  laravel_db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_db
    restart: always
    volumes:
      - laravel-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  laravel_cache:
    image: redis:5.0-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_cache
    restart: always
    expose:
      - "6379"

volumes:
  laravel-db:
  laravel-storage:
