apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_production_nginx:latest
          name: backend-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-php
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_production_php:latest
          name: backend-php
          env:
          - name: aliyun_logs_elasticsearch-production-php-stdout
            value: stdout
      volumes:
        - name: yii-runtime
          persistentVolumeClaim:
            claimName: elasticsearch-production-yii-runtime-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yii-runtime
spec:
  capacity:
    storage: 50Gi
  csi:
    volumeAttributes:
      server: "31d62494e0-rth47.cn-shanghai.nas.aliyuncs.com"
      path: "/mnt/elasticsearch-production-yii-runtime"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yii-runtime-claim
  namespace: default
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-test
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_production_php:latest
              name: cronjob-test
