apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: elasticsearch-production-
commonLabels:
  app: elasticsearch
bases:
  - ../../base/apps
  - ../../base/db
patchesStrategicMerge:
  - backend/overlays.yaml
  - mysql/overlays.yaml
# resources:
#- backend/configmap.yaml
#- mysql/configmap.yaml
#- redis/configmap.yaml

configMapGenerator:
  - name: public-overlays
    literals:
      - api_host=es-api.818ps.com
      - admin_host=es-api.818ps.com
      - DB_CONNECTION=mysql
      - DB_HOST=elasticsearch-production-mysql
      - DB_PORT=3306
      - DB_DATABASE=domain
      - DB_PREFIX=es_
      - LARAVEL_HTTP_PORT=9000
      - APP_NAME="elasticsearch"
      - APP_ENV=production
      - APP_KEY=base64:gT5YBxoHuFZqzPGU9CO26koLyE6YQkkLK+cH9dKQD8g=
      - APP_DEBUG=false
      - APP_TIMEZONE=Asia/Shanghai
      - APP_LOCALE=zh-CN
      - LOG_CHANNEL=errorlog
      - REDIS_CLIENT=phpredis
      - REDIS_CLUSTER=phpredis
      - REDIS_HOST=elasticsearch-production-cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - JWT_SECRET=N0FZnCy8MBBaLKsIcGN8ugJhQdPOjpXNsEiXigeyl1fy47vpuuo5GROeXp1aMyVw
      - JWT_TTL=86400
