apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: elasticsearch-staging-
commonLabels:
  app: elasticsearch
bases:
  - ../../base/apps
  - ../../base/db
patchesStrategicMerge:
  - backend/overlays.yaml
  - mysql/overlays.yaml
# resources:
#- backend/configmap.yaml
#- mysql/configmap.yaml
#- redis/configmap.yaml

images:
  - name: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_staging_nginx
    newTag: MYNEWTAG
  - name: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_staging_php
    newTag: MYNEWTAG

configMapGenerator:
  - name: public-overlays
    literals:
      - api_host=es-api-staging.818ps.com
      - admin_host=es-api-staging.818ps.com
      - UNIT_BASE_URL=https://818ps.com
      - APP_NAME="ElasticSearch"
      - APP_ENV=staging
      - APP_KEY=base64:gT5YBxoHuFZqzPGU9CO26koLyE6YQkkLK+cH9dKQD8g=
      - APP_DEBUG=true
      - APP_TIMEZONE=Asia/Shanghai
      - APP_LOCALE=zh-CN
      - LOG_CHANNEL=errorlog
      - DB_CONNECTION=mysql
      - DB_HOST=elasticsearch-staging-mysql
      - DB_PORT=3306
      - DB_DATABASE=domain
      - DB_PREFIX=es_
      - REDIS_HOSTNAME=r-uf6ho5b75zcknf33lr.redis.rds.aliyuncs.com
      - REDIS_SESSION_HOSTNAME=r-uf6sl57iwn5z61ssjo.redis.rds.aliyuncs.com
      - REDIS_SEARCH_HOSTNAME=r-uf6an0ba8tty6e8v03.redis.rds.aliyuncs.com
      - ELASTIC_HOST=192.168.5.31:9200
      - ELASTIC_COLOR_HOST=192.168.4.211:9200
      - ELASTIC_KEYWORD_HOST=192.168.4.86:9200
      - ELASTIC_SECOND_HOST=192.168.4.194:9200

