apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: elasticsearch-staging-
commonLabels:
  app: elasticsearch
bases:
  - ../../base/apps
  - ../../base/db
patchesStrategicMerge:
  - backend/overlays.yaml
  - mysql/overlays.yaml
# resources:
#- backend/configmap.yaml
#- mysql/configmap.yaml
#- redis/configmap.yaml

images:
  - name: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_staging_nginx
    newTag: MYNEWTAG
  - name: registry-vpc.cn-shanghai.aliyuncs.com/818ps/elasticsearch_staging_php
    newTag: MYNEWTAG

configMapGenerator:
  - name: public-overlays
    literals:
      - api_host=es-api-staging.818ps.com
      - admin_host=es-api-staging.818ps.com
      - DB_CONNECTION=mysql
      - DB_HOST=elasticsearch-staging-mysql
      - DB_PORT=3306
      - DB_DATABASE=domain
      - DB_PREFIX=es_
      - APP_NAME="ElasticSearch"
      - APP_ENV=staging
      - APP_KEY=base64:gT5YBxoHuFZqzPGU9CO26koLyE6YQkkLK+cH9dKQD8g=
      - APP_DEBUG=true
      - APP_TIMEZONE=Asia/Shanghai
      - APP_LOCALE=zh-CN
      - LOG_CHANNEL=errorlog
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_CLIENT=phpredis
      - REDIS_CLUSTER=phpredis
      - REDIS_HOST=elasticsearch-staging-cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - JWT_SECRET=N0FZnCy8MBBaLKsIcGN8ugJhQdPOjpXNsEiXigeyl1fy47vpuuo5GROeXp1aMyVw
      - JWT_TTL=86400
